/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/ActionBar.vue')['default']
    ActionDialog: typeof import('./src/components/ActionDialog.vue')['default']
    ActionPanel: typeof import('./src/components/ActionPanel.vue')['default']
    AppToast: typeof import('./src/components/AppToast.vue')['default']
    HotkeyRecorder: typeof import('./src/components/HotkeyRecorder.vue')['default']
    InputBar: typeof import('./src/components/InputBar.vue')['default']
    KeyboardKey: typeof import('./src/components/KeyboardKey.vue')['default']
    LoadingBar: typeof import('./src/components/LoadingBar.vue')['default']
    LoadingIcon: typeof import('./src/components/LoadingIcon.vue')['default']
    PublicLayout: typeof import('./src/components/PublicLayout.vue')['default']
    ResultItem: typeof import('./src/components/ResultItem.vue')['default']
    ResultItemPreview: typeof import('./src/components/ResultItemPreview.vue')['default']
    ResultView: typeof import('./src/components/ResultView.vue')['default']
    RoutePage: typeof import('./src/components/RoutePage.vue')['default']
    ShortcutsKey: typeof import('./src/components/ShortcutsKey.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap_dcb37bfa4d18d5120c3b1bcf83d10be6/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap_dcb37bfa4d18d5120c3b1bcf83d10be6/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap_dcb37bfa4d18d5120c3b1bcf83d10be6/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap_dcb37bfa4d18d5120c3b1bcf83d10be6/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap_dcb37bfa4d18d5120c3b1bcf83d10be6/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UKbd: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap_dcb37bfa4d18d5120c3b1bcf83d10be6/node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap_dcb37bfa4d18d5120c3b1bcf83d10be6/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USwitch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap_dcb37bfa4d18d5120c3b1bcf83d10be6/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
  }
}
