hoist: true

linkWorkspacePackages: true

ignore-workspace-root-check: true

useNodeVersion: 24.11.1

packages:
  - src-node
  - packages/*
  - plugins/*

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - vue-demi

catalog:
  typescript: ~5.9.2

catalogs:
  plugin:
    "@rollup/plugin-commonjs": ^28.0.6
    "@rollup/plugin-node-resolve": ^16.0.1
    rollup: ^4.46.2
    rollup-plugin-esbuild: ^6.2.1
    "@rollup/plugin-replace": ^6.0.2
    "@rollup/plugin-json": ^6.1.0
