
ignoreWorkspaceRootCheck: true

useNodeVersion: 24.11.1

packages:
  - src-node
  - packages/*
  - plugins/*
  - store/plugins/*
  - src-tauri/plugins/double-tap-shortcut/guest-js

catalog:
  typescript: ~5.9.2

catalogs:
  plugin:
    tsdown: ^0.21.7
engineStrict: true
hoist: true

linkWorkspacePackages: true

nodeVersion: 24.5.0

onlyBuiltDependencies:
  - better-sqlite3
  - electron
  - esbuild
  - sharp
  - vue-demi
