name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]

    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Rust setup
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: "1.90"
        components: rustfmt, clippy

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Sync node version and setup cache
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: pnpm

    - name: Install frontend dependencies
      run: pnpm install --frozen-lockfile --ignore-scripts

    - name: Import Apple Developer Certificate
      env:
        APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
        APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12
        security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security set-keychain-settings -t 3600 -u build.keychain
        security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
        security find-identity -v -p codesigning build.keychain
    - name: Verify Certificate
      run: |
        CERT_INFO=$(security find-identity -v -p codesigning build.keychain)
        CERT_ID=$(echo "$CERT_INFO" | awk -F'"' '{print $2}')
        echo "CERT_ID=$CERT_ID" >> $GITHUB_ENV
        echo "Certificate imported."

    - name: Build the app
      run: pnpm run app:build
      env:
        TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-artifacts
        path: |
          src-tauri/target/release/bundle/
          src-tauri/target/debug/bundle/